---
AWSTemplateFormatVersion: '2010-09-09'
Description: DNS Zone and SSL creation
Parameters:
  DomainName:
    Type: String
    Description: The DNS name of an Amazon Route 53 hosted zone e.g. server.com
    AllowedPattern: '(?!-)[a-zA-Z0-9-.]{1,63}(?<!-)'
    ConstraintDescription: must be a valid DNS zone name.

Resources:

  DNS:
    Type: AWS::Route53::HostedZone
    Properties:
      HostedZoneConfig:
        Comment: !Join [' ', ['Hosted zone for', !Ref DomainName]]
      Name: !Ref DomainName

  SSL:
    Type: AWS::CertificateManager::Certificate
    Properties: 
      DomainName: !Ref DomainName
      DomainValidationOptions: 
        - DomainName: !Join ['.', ['api', !Ref DomainName]]
          HostedZoneId: !Ref DNS
      SubjectAlternativeNames: 
        - !Join ['.', ['*', !Ref DomainName]]
      ValidationMethod: DNS
